#!/bin/bash
#
# kickstart
# 
# chkconfig: 2345 99 99
# description: VM Kickstart from URL

function kickstart(){
    CURL=`which curl`
    XENSTOREREAD=`which xenstore-read`
    KICKSTART_STATUS=/etc/sysconfig/kickstart

    [ -x $XENSTOREREAD ] || exit 255
    [ -x $CURL ] || exit 255

    KICKSTART_URL=`$XENSTOREREAD vm-data/ks`
    [ "$KICKSTART_URL" = "" ] && exit 0
    $CURL -k $KICKSTART_URL 2>/dev/null|bash
}




case "$1" in
    start)
        kickstart
        chkconfig kickstart off
        ;;
    stop|status|restart|reload|force-reload)
        # do nothing
        ;;
esac
