#!/bin/bash
#
# xe-automater
# 
# chkconfig: 2345 85 15
# description: XenServer Guest Configuration Automator

case "$1" in
  start)
    /usr/sbin/xe-set-network
    /usr/sbin/xe-set-hostname
    /usr/sbin/xe-set-authorized-keys
    chkconfig xe-automater off
  ;;
  stop|status|restart|reload|force-reload)
    # do nothing
  ;;
esac
