#!/bin/bash
#
# xe-automater
# 
# chkconfig: 2345 9 20
# description: XenServer Guest Configuration Automator

case "$1" in
  start)
    /usr/sbin/xe-set-network
    /usr/sbin/xe-set-hostname
    [ -f /etc/ssh/ssh_host_rsa_key ] && rm /etc/ssh/ssh_host_rsa_key
    chkconfig xe-automater off
  ;;
  stop|status|restart|reload|force-reload)
    # do nothing
  ;;
esac
