#!/bin/bash
XENSTOREREAD=`which xenstore-read`

[ -x $XENSTOREREAD ] || exit 0

IP=`$XENSTOREREAD vm-data/ip`
GW=`$XENSTOREREAD vm-data/gw`
NM=`$XENSTOREREAD vm-data/nm`
NS=`$XENSTOREREAD vm-data/ns`
DM=`$XENSTOREREAD vm-data/dm`

[ "$IP" = "" ] && exit 0
[ "$GW" = "" ] && exit 0
[ "$NM" = "" ] && exit 0
[ "$NS" = "" ] && exit 0
[ "$DM" = "" ] && exit 0

cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
BOOTPROTO=static
ONBOOT=yes
NM_CONTROLLED=yes
IPADDR=$IP
NETMASK=$NM
EOF

cat << EOF > /etc/sysconfig/network
NETWORKING=yes
HOSTNAME=$NAME.$DOMAIN
GATEWAY=$IP
EOF

cat << EOF > /etc/resolv.conf
search $DOMAIN
nameserver $NS
EOF

/etc/init.d/network restart

exit 0
