#!/bin/bash
XENSTOREREAD=`which xenstore-read`
if [ -e $XENSTOREREAD ]; then
  NAME=`$XENSTOREREAD name`
  DOMAIN=`$XENSTOREREAD vm-data/dm`

  # require both the name and domain to alter configuration
  [ "$NAME" = "" ] && exit 0
  [ "$DOMAIN" = "" ] && exit 0

  sed -r "s/HOSTNAME=.*\$/HOSTNAME=$NAME.$DOMAIN/" /etc/sysconfig/network

  # read passed in IP address if it exists
  IP=`$XENSTOREREAD vm-data/ip`
  # otherwise just use the ip address that the machine has already
  if [ $IP = "" ]; then IP=`ip addr list eth0 |grep "inet " |cut -d' ' -f6|cut -d/ -f1`; fi

cat << EOF > /etc/hosts
127.0.0.1	localhost
$IP	$NAME.$DOMAIN	$NAME	
EOF
	
fi
exit 0

